#ifndef CHRDEV_IOCTL_H
#define CHRDEV_IOCTL_H

#define CHRDEV_IOC_MAGIC 'k'

enum chrdev_ioc {
	CHRDEV_CBUFF,
	CHRDEV_GBUFF_LEN,
	CHRDEV_SBUFF_LEN,
	CHRDEV_MAX
};

#define CHRDEV_IOCCBUFF		_IO(CHRDEV_IOC_MAGIC, CHRDEV_CBUFF)
#define CHRDEV_IOCGBUFF_LEN	_IOR(CHRDEV_IOC_MAGIC, CHRDEV_GBUFF_LEN, size_t *)
#define CHRDEV_IOCSBUFF_LEN	_IOW(CHRDEV_IOC_MAGIC, CHRDEV_SBUFF_LEN, size_t *)


#endif /* CHRDEV_IOCTL_H */