#ifndef __CHRDEV_IOCTL_H__
#define __CHRDEV_IOCTL_H__

#define CLASS_NAME "chrdev"
#define DEVICE_NAME "chrdev_simple"
#define CDEV_FILE "/dev/chrdev0"

#define CDEV_IOC_MAGIC 'V'

enum cdev_ioctl {
	WR_VALUE,
	RD_VALUE,
	CLEAR_BUFFER,
	GET_BUFFER_SIZE,
	SET_BUFFER_SIZE,
	CDEV_IOC_MAXNR, /* keep last */
};

#define CDEV_WR_VALUE        _IOW(CDEV_IOC_MAGIC, WR_VALUE, int32_t*)
#define CDEV_RD_VALUE        _IOR(CDEV_IOC_MAGIC, RD_VALUE, int32_t*)
#define CDEV_CLEAR_BUFFER    _IO(CDEV_IOC_MAGIC, CLEAR_BUFFER)
#define CDEV_GET_BUFFER_SIZE _IOR(CDEV_IOC_MAGIC, GET_BUFFER_SIZE, int32_t*)
#define CDEV_SET_BUFFER_SIZE _IOW(CDEV_IOC_MAGIC, SET_BUFFER_SIZE, int32_t*)
#define CDEV_WRRD_ARR_VALUE  _IOWR(CDEV_IOC_MAGIC, SET_BUFFER_SIZE, int32_t*)



#endif /* __CHRDEV_IOCTL_H__ */