#ifndef __cdev_ioctl_h__
#define __cdev_ioctl_h__

#define CDEV_IOC_MAGIC 'J'


enum chardev_ioctl {
	CLEAR_BUFFER,
	GET_FONT_SIZE,
	SET_FONT_SIZE,
	GET_TEXT_COLOR,
	SET_TEXT_COLOR,
	GET_BG_COLOR,
	SET_BG_COLOR,
	CDEV_IOC_MAXNR
};

#define CDEV_CLEAR_BUFFER _IO(CDEV_IOC_MAGIC, CLEAR_BUFFER)
#define CDEV_GET_FONT_SIZE _IOR(CDEV_IOC_MAGIC, GET_FONT_SIZE, int16_t*)
#define CDEV_SET_FONT_SIZE _IOW(CDEV_IOC_MAGIC, SET_FONT_SIZE, int16_t*)

#define CDEV_GET_TEXT_COLOR _IOR(CDEV_IOC_MAGIC, GET_TEXT_COLOR, int16_t*)
#define CDEV_SET_TEXT_COLOR _IOW(CDEV_IOC_MAGIC, SET_TEXT_COLOR, int16_t*)

#define CDEV_GET_BG_COLOR _IOR(CDEV_IOC_MAGIC, GET_BG_COLOR, int16_t*)
#define CDEV_SET_BG_COLOR _IOW(CDEV_IOC_MAGIC, SET_BG_COLOR, int16_t*)

enum encoder_ioctl {
	GET_ENCODER,
	SET_ENCODER,
	GET_DEBOUNCE_DELAY,
	SET_DEBOUNCE_DELAY,
	ENC_IOC_MAXNR
};

#define CDEV_GET_ENCODER _IOR(CDEV_IOC_MAGIC, GET_ENCODER, int32_t*)
#define CDEV_SET_ENCODER _IOW(CDEV_IOC_MAGIC, SET_ENCODER, int32_t*)

#define CDEV_GET_DEBOUNCE_DELAY _IOR(CDEV_IOC_MAGIC, GET_DEBOUNCE_DELAY, int32_t*)
#define CDEV_SET_DEBOUNCE_DELAY _IOW(CDEV_IOC_MAGIC, SET_DEBOUNCE_DELAY, int32_t*)

enum temp_ioctl {
	GET_TEMP,
	GET_TIMEOUT,
	SET_TIMEOUT,
	TEMP_IOC_MAXNR
};

#define CDEV_GET_TEMP _IOR(CDEV_IOC_MAGIC, GET_TEMP, int32_t*)
#define CDEV_GET_TIMEOUT _IOR(CDEV_IOC_MAGIC, GET_TIMEOUT, int32_t*)
#define CDEV_SET_TIMEOUT _IOW(CDEV_IOC_MAGIC, SET_TIMEOUT, int32_t*)


#endif /* __cdev_ioctl_h__ */
